### ISSUE TITLE
flutter: Warning: Falling back on slow accent color resolution. 

### ISSUE THREAD

**Issue by les-larsj** [macosui/macos_ui#495]
Hi,

As requested by the error message below I am letting you know that I get this error whenever I try to restart my app **but** not when I stop the app and then start a new debug session:

**Restarted application in 1,369ms.
flutter: Warning: Falling back on slow accent color resolution. It’s possible that the accent colors have changed in a recent version of macOS, thus invalidating macos_ui’s accent colors, which were captured on macOS Ventura. If you see this message, please notify a maintainer of the macos_ui package.**

I am running Ventura 13.6.1 on my 2017 iMac with quad core i5 and 32GB RAM.

In case it helps this is the relevant part of my pubspec.yaml:

```
environment:
  sdk: '>=3.1.2 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  bloc: ^8.1.2
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  macos_ui: ^2.0.0
  provider: ^6.0.5
  freezed_annotation: ^2.4.1
  freezed: ^2.4.5
  loggy: ^2.0.3
  sentry: ^7.10.1
  sentry_flutter: ^7.10.1
  get_it: ^7.6.4
  injectable: ^2.3.2
  build_runner: ^2.4.6
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.4.1

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

```
and here is my "flutter doctor -v" output:

[✓] Flutter (Channel stable, 3.13.9, on macOS 13.6.1 22G313 darwin-x64, locale en-GB)
    • Flutter version 3.13.9 on channel stable at /Users/les/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d211f42860 (2 weeks ago), 2023-10-25 13:42:25 -0700
    • Engine revision 0545f8705d
    • Dart version 3.1.5
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/les/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.13.0

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Applications/Vivaldi.app/Contents/MacOS/Vivaldi

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /Applications/Android Studio.app
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.84.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.76.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 13.6.1 22G313 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Vivaldi 6.4.3160.41

[✓] Network resources
    • All expected network resources are available.

Please let me know if you need anymore info from me.

Les

**Comment by Adrian-Samoticha** [comment]
Sorry for taking so long to respond and thanks for notifying us of the issue. Did you, by chance, edit your app’s accent color in Xcode?

**Comment by les-larsj** [comment]
Hi Adrian,
No, I didn't but it has been so long that I completely forgot about this and it is no longer happening with my current setup:

```
[!] Flutter (Channel stable, 3.19.5, on macOS 14.4.1 23E224 darwin-arm64, locale en-GB)
    • Flutter version 3.19.5 on channel stable at /Users/les/fvm/versions/3.19.4
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/3.3.3/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /Users/les/fvm/versions/3.19.4. Consider adding
      /Users/les/fvm/versions/3.19.4/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 300451adae (6 days ago), 2024-03-27 21:54:07 -0500
    • Engine revision e76c956498
    • Dart version 3.3.3
    • DevTools version 2.31.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.
```

and these versions of packages in my pub spec.yaml:

```
dependencies:
  bloc: ^8.1.4
  build_runner: ^2.4.8
  cupertino_icons: ^1.0.2
  dropdown_search: ^5.0.6
  equatable: ^2.0.5
  file_picker: ^8.0.0+1
  file_selector: ^1.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_form_builder: ^9.2.1
  form_builder_validators: ^9.1.0
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1
  get_it: ^7.6.7
  injectable: ^2.3.3
  intl: ^0.18.1
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  loggy: ^2.0.3
  macos_ui: ^2.0.5
  package_info_plus: ^5.0.1
  path_provider: ^2.1.2
  provider: ^6.1.2
  sentry: ^7.18.0
  sentry_flutter: ^7.18.0
  talker: ^4.0.3
  window_manager: ^0.3.8

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.4.2
```

If it happens again I will let you know but I guess you can close this issue for now if you want to.
